//%attributes = {"invisible":true}
// First launch: fill an empty data file with the sample data for the current language
// (Resources/<lang>.lproj/data.sql, generated by data/ORDAEvents/make_seed.py)

If (ds:C1482.Client.all().length=0) && (ds:C1482.Product.all().length=0) && (ds:C1482.Order.all().length=0)
	
	var $file : 4D.File
	$file:=Folder(fk resources folder).folder(Get database localization(Current localization)+".lproj").file("data.sql")
	If (Not($file.exists))
		$file:=Folder(fk resources folder).folder("en.lproj").file("data.sql")
	End if 
	
	SQL EXECUTE SCRIPT($file.platformPath; SQL On error abort)
	
End if 