//%attributes = {"invisible":true}
// First launch: fill an empty data file with the sample data for the current language
// (Resources/<lang>.lproj/data.sql, generated by data/ORDAEvents/make_seed.py)

var $dataClassName : Text
For each ($dataClassName; ds:C1482)
	If (ds:C1482[$dataClassName].getCount()#0)
		return 
	End if 
End for each 

var $path : Text
$path:=Localized document path:C1105("data.sql")
If (Test path name:C476($path)=Is a document:K24:1)
	SQL EXECUTE SCRIPT:C1089($path; SQL On error confirm:K49:16)
End if 

00_Start